### ISSUE TITLE
NPM package

### ISSUE THREAD

**Issue by justgage** [astrada/ppx_bs_css#26]
Is there an NPM package, I love how this looks, would love to try it.

**Comment by astrada** [comment]
No, sorry, I didn't have time to prepare a pre-compiled package.

**Comment by justgage** [comment]
No problem, I totally understand 👍. Open Source isn't free.

**Comment by shrynx** [comment]
@astrada

i have a working version ready using the ci templates from [esy examples](https://github.com/esy-ocaml/hello-reason/tree/master/.ci) and [bs-log-ppx](https://github.com/minima-app/bs-log)

here is a published version i tried to check the ci 
[@shriyans/ppx_bs_css](https://www.npmjs.com/package/@shriyans/ppx_bs_css)

instruction:
- `yarn add -D @shriyans/ppx_bs_css`
- add to bsconfig.json
```
{
..
 "ppx-flags": ["@shriyans/ppx_bs_css/ppx"]

}
```
(sorry i published this without asking 😬, i'll delete it  once i upstream the change)

i can make a PR sometime tonight or tomorrow sometime

**Comment by shrynx** [comment]
pr opened #27 🙂
