### ISSUE TITLE
How did you implement the suggestion feature?

### ISSUE THREAD

**Issue by dylanirlbeck** [astrada/ppx_bs_css#34]
I'm curious how you implemented the "suggestion" (i.e. "Did you mean ___?") feature since I don't see it in the code. Thanks in advance!

![color_typo](https://user-images.githubusercontent.com/35497479/80554962-7176d600-8994-11ea-882e-e0df3633ea60.png)

**Comment by astrada** [comment]
Well, it'a feature of the OCaml compiler (colors and formatting are a customization of BuckleScript). `bs-css` has a value named `yellow` that's in scope, the compiler does a minimum distance search to propose the hint.

**Comment by dylanirlbeck** [comment]
Awesome, thanks. I see now the PPX transforms these into values (rather than just operating on strings) so you get those free compiler benefits.
