### ISSUE TITLE
Are select and pseudo selectors in TypedGlamor supported?

### ISSUE THREAD

**Issue by jchavarri** [astrada/ppx_bs_css#4]
I'm trying to add some pseudo selectors inside the ` [%style {typed|...|typed} ]` declarations, but I'm getting syntax errors.

Are `hover`, `select` and other Glamor selectors supported? Maybe I'm using the wrong syntax. I took a look at the code, readme + examples in https://github.com/astrada/ppx_bs_css-examples/tree/master/packages/styled-react but haven't seen any case with `typed` and selectors.

Thanks!

**Comment by astrada** [comment]
I think this should work:

```reason
/* Selectors */
let _ = {
  let open TypedGlamor;
  [%css
    {typed|
      {
        color: red;
      }

      :hover {
        color: blue;
      }
    |typed}
  ];
};
```

**Comment by jchavarri** [comment]
Thanks! It works!  ✨
