### ISSUE TITLE
font-family support

### ISSUE THREAD

**Issue by jchavarri** [astrada/ppx_bs_css#7]
There seems to be a few challenges with font families:

1. The `font-family` values don't have quotes around them, so:

```
[%style
  {typed|
  font-family: Helvetica;
  |typed}
]
```

fails to compile, as `Helvetica` gets compiled as is, but it is not defined.

2. Some font family names have spaces. For example:

```
[%style
  {typed|
  font-family: Helvetica Neue;
  |typed}
]
```

Gets interpreted as two values right now, and fails as "`fontFamily2` can't be found".

3. A set of families uses commas to separate:

```
[%style
  {typed|
  font-family: Helvetica, Arial;
  |typed}
]
```

fails with "Unsupported delimiter".

**Comment by astrada** [comment]
Should be fixed in branch [issue7](https://github.com/astrada/ppx_bs_css/tree/issue7). If you can confirm, I will merge it to master. Thanks!

**Comment by jchavarri** [comment]
Woah that was fast ⚡️ It works great! 👍
